In [1]:
sent1='It is good for our progress'
sent2='they have decided that it was not good'

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
cvt=CountVectorizer()

In [4]:
vect=cvt.fit_transform([sent1,sent2])

In [5]:
import pandas as pd

In [6]:
df=pd.DataFrame(vect.toarray(),columns=cvt.get_feature_names_out())
df

decided  for  good  have  is  it  not  our  progress  that  they  was
0        0    1     1     0   1   1    0    1         1     0     0    0
1        1    0     1     1   0   1    1    0         0     1     1    1

In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
Lines=['It was a nice rainy day.',
'The things are so beautiful in his point.',
'when your focus is clear ,you won.',
'many many happy returns of the day.']

In [9]:
Lines[0].split()

['It', 'was', 'a', 'nice', 'rainy', 'day.']

In [10]:
tokenizer=Tokenizer()
tokenizer .fit_on_texts(Lines)
tokenizer.word_counts

OrderedDict([('it', 1),
             ('was', 1),
             ('a', 1),
             ('nice', 1),
             ('rainy', 1),
             ('day', 2),
             ('the', 2),
             ('things', 1),
             ('are', 1),
             ('so', 1),
             ('beautiful', 1),
             ('in', 1),
             ('his', 1),
             ('point', 1),
             ('when', 1),
             ('your', 1),
             ('focus', 1),
             ('is', 1),
             ('clear', 1),
             ('you', 1),
             ('won', 1),
             ('many', 2),
             ('happy', 1),
             ('returns', 1),
             ('of', 1)])

In [11]:
tokenizer.word_index

{'day': 1,
 'the': 2,
 'many': 3,
 'it': 4,
 'was': 5,
 'a': 6,
 'nice': 7,
 'rainy': 8,
 'things': 9,
 'are': 10,
 'so': 11,
 'beautiful': 12,
 'in': 13,
 'his': 14,
 'point': 15,
 'when': 16,
 'your': 17,
 'focus': 18,
 'is': 19,
 'clear': 20,
 'you': 21,
 'won': 22,
 'happy': 23,
 'returns': 24,
 'of': 25}

In [12]:
mat=tokenizer.texts_to_matrix(Lines)
mat

array([[0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [13]:
seq=tokenizer.texts_to_sequences(Lines)
seq

[[4, 5, 6, 7, 8, 1],
 [2, 9, 10, 11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20, 21, 22],
 [3, 3, 23, 24, 25, 2, 1]]

In [14]:
padded=pad_sequences(seq,maxlen=10,padding='pre')
padded

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  1],
       [ 0,  0,  2,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  0,  0, 16, 17, 18, 19, 20, 21, 22],
       [ 0,  0,  0,  3,  3, 23, 24, 25,  2,  1]], dtype=int32)

In [15]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , LSTM,Dense
from sklearn.model_selection import train_test_split
import re
import numpy as np

In [16]:
data=pd.read_csv("twitter_sentiments.csv",names=['id','loc','label','text'])
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
74677  Just realized that the Windows partition of my...  
74678  Just realized that my Mac window partition is ...  
74679  Just realized the windows partition of my Mac ...  
74680  Just realized between the windows partition of...  
74681  Just like the windows partition of my Mac is l...  

[74682 rows x 4 columns]

In [17]:
data.shape

(74682, 4)

In [18]:
data.dtypes

id        int64
loc      object
label    object
text     object
dtype: object

In [19]:
data['text']=data['text'].astype(str)

In [20]:
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
74677  Just realized that the Windows partition of my...  
74678  Just realized that my Mac window partition is ...  
74679  Just realized the windows partition of my Mac ...  
74680  Just realized between the windows partition of...  
74681  Just like the windows partition of my Mac is l...  

[74682 rows x 4 columns]

In [21]:
def clean_text(text):
 text=text.lower()
 text=re.sub(r"[^a-zA-Z]+"," ",text)
 return text

In [22]:
clean_text("hello friends! how are you?? welcome..62782!!!")

'hello friends how are you welcome '

In [23]:
data["text"]=data["text"].apply(clean_text)

In [24]:
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      i am coming to the borders and i will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands and i will murder yo...  
...                                                  ...  
74677  just realized that the windows partition of my...  
74678  just realized that my mac window partition is ...  
74679  just realized the windows partition of my mac ...  
74680  just realized between the windows partition of...  
74681  just like the windows partition of my mac is l...  

[74682 rows x 4 columns]

In [25]:
comments=data["text"].tolist()
targets=data['label'].values

In [26]:
pd.DataFrame(targets).value_counts()

0         
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [27]:
##generate training data
tokenizer=Tokenizer(num_words=5000)
tokenizer.fit_on_texts(comments)
sequences=tokenizer.texts_to_sequences(comments)
padded_sequences=pad_sequences(sequences,maxlen=200)

In [28]:
padded_sequences.shape

(74682, 200)

In [29]:
padded_sequences

array([[   0,    0,    0, ..., 1695,   12,   26],
       [   0,    0,    0, ...,  424,   12,   26],
       [   0,    0,    0, ...,  424,   12,   26],
       ...,
       [   0,    0,    0, ...,  302,   15, 2055],
       [   0,    0,    0, ...,  302,   15, 2055],
       [   0,    0,    0, ...,  302,   15, 2055]], dtype=int32)

In [30]:
#output data preparation
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(targets)
from keras.utils import to_categorical
y_new=to_categorical(y)

In [31]:
y_new

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [32]:
x_train,x_test,y_train,y_test=train_test_split( padded_sequences,y_new,test_size=0.2,random_state=0)

In [33]:
x_train.shape

(59745, 200)

In [34]:
x_test.shape

(14937, 200)

In [35]:
# c.train the model
model=Sequential()
model.add(Embedding(5000,128, input_length=200))
model.add(LSTM(64))
model.add(Dense(4,activation='softmax'))

C:\Users\shiva\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [36]:
model.compile(loss='categorical_crossentropy',optimizer="adam",metrics=['accuracy'])

In [37]:
model.fit(x_train,y_train,epochs=3,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/3
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 322s 170ms/step - accuracy: 0.6199 - loss: 0.9262 - val_accuracy: 0.7103 - val_loss: 0.7395
Epoch 2/3
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 315s 169ms/step - accuracy: 0.7677 - loss: 0.6039 - val_accuracy: 0.7685 - val_loss: 0.6066
Epoch 3/3
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 308s 165ms/step - accuracy: 0.8294 - loss: 0.4508 - val_accuracy: 0.7987 - val_loss: 0.5427


In [38]:
new_comment=' I hate mango'
new_sequence=tokenizer.texts_to_sequences([clean_text(new_comment)])
padded_new_sequence=pad_sequences(new_sequence,maxlen=200)
prediction=model.predict(padded_new_sequence)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 561ms/step


In [39]:
prediction

array([0.25600702, 0.6007843 , 0.11050313, 0.03270548], dtype=float32)

In [40]:
le.inverse_transform([np.argmax(prediction)])[0]

'Negative'